### ISSUE TITLE
Use tags for versioning

### ISSUE THREAD

**Issue by alexschwarz89** [Cidaas/oauth2-cidaas-php#5]
The usage of "dev-master" should be avoided, as it would pull any (possible breaking change) in a composer update procedure. Please use tags for versioning, i see there is a 1.0.0 tag, but its not installable via composer, probably you need to push it to packagist: https://packagist.org/?query=cidaas-sdk-php

**Comment by Grossmann-Widas** [comment]
Hi, there was a version mismatch between the composer.json & the released tag 1.0.0. I have removed the version info from the composer.json as advised, and published a new tag 1.1.0.  This should now be install able via packagist.
