### ISSUE TITLE
Update Guzzle dependency to satisfy security wise stable version

### ISSUE THREAD

**Issue by gartenumgraben** [Cidaas/oauth2-cidaas-php#6]
Version 6.3 is no longer save, see: 

 https://github.com/guzzle/guzzle#version-guidance 

Please update the dependency accordingly.

**Comment by skurrilo** [comment]
which version/branch are you using? the current master has 7.2 in composer.json.

see: https://github.com/Cidaas/cidaas-sdk-php/blob/5206caf7347dccd5a7a17f116ed20df4ca693391/composer.json#L23

**Comment by gartenumgraben** [comment]
Iam serving it to 2 different systems none of which  can use the master.

**System A**
- old system running for years
- uses dev-cidaas-v2
- PHP 7.2.23
- since a recent security update the underlying system requires: "guzzlehttp/guzzle": "^6.5.8" 

**System B**
- "new" system the old one is curently beeing migrated to
- PHP 7.4.29  (will become 8.x evetualy)
- since a recent security update the underlying system requires: guzzlehttp/guzzle: ^6.5.8

**Comment by Nirukamath** [comment]
Please use the latest SDK version: https://github.com/Cidaas/cidaas-sdk-php/releases/tag/v1.2.0

**Comment by gartenumgraben** [comment]
Iam sorry but the stated version still requires "guzzlehttp/guzzle": "^7.2.0" wich does not comply with my requirements of  "guzzlehttp/guzzle": "^6.5.8"

Am I missing something?

**Comment by Nirukamath** [comment]
Sorry, but we do not provide a downgrade to lower versions.
